### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#1]
Variations:

  * `vscode-sass`: `Sass IntelliSense` (but we support only SCSS syntax)
  * `vscode-scss`: `SCSS IntelliSense` (but SCSS is Sass)
  * `???`

**Comment by michaeljota** [comment]
I think it's better to say it's an intellisense scss... So `scss-intellisense` (?)

vscode already have support for the language, so it could be redundant to say `vscode-sass`/`vscode-scss`

**Comment by mrmlnc** [comment]
@michaeljota,

Thanks, for your ideas.

I think, `vscode-scss` (identifier) + `SCSS IntelliSense` (name) sounds good.

**Comment by michaeljota** [comment]
Looking forward to work with this! 😄 Thanks you!
