### ISSUE TITLE
Avoid using rootPath

### ISSUE THREAD

**Issue by roblourens** [mrmlnc/vscode-scss#106]
This extension appears to be using rootPath from the LSP. This is a deprecated property that may not work as expected in a multi-root workspace.

See this guide on implementing multi-root support: https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#language-client--language-server

microsoft/vscode#69335

**Comment by gjsjohnmurray** [comment]
@mrmlnc it would be nice to get this resolved so the related VS Code issue has one less popular extension to worry about breaking.
