### ISSUE TITLE
Error request textDocument/signatureHelp

### ISSUE THREAD

**Issue by druellan** [mrmlnc/vscode-scss#11]
Using the plugin version 0.3.1 and Code 1.6.1, sometimes I get this error message:

![2016-10-26_00h22_39](https://cloud.githubusercontent.com/assets/6965667/19712372/8614560a-9b13-11e6-85a0-4b0c302412e2.png)

I still can't reproduce it at will, but seems to happen when I'm editing a scss value on the middle of a property list, for example:

![2016-10-26_00h32_47](https://cloud.githubusercontent.com/assets/6965667/19712389/be6568a0-9b13-11e6-86b0-e75f78faa201.png)

**Comment by mrmlnc** [comment]
Fixed in **0.4.0**.
