### ISSUE TITLE
Initialization error, immediately after installation.

### ISSUE THREAD

**Issue by shurinskiy** [mrmlnc/vscode-scss#119]
![2](https://user-images.githubusercontent.com/7316438/83881080-f4443b00-a761-11ea-9d36-50fdc0aeb109.JPG)
![1](https://user-images.githubusercontent.com/7316438/83881088-f7d7c200-a761-11ea-9963-5cf28f35eda4.JPG)

**Comment by mrmlnc** [comment]
I ship the next version (`0.10.0`) of this plugin to the VS Code Marketplace. Is the problem still there?

If so, please provide more information about your environment. If there is an opportunity to provide a project (on GitHub, as archive on email) or a minimally reproducible case (better case), it would help a lot.
