### ISSUE TITLE
Show all All Symbol Definitions in Folder (CTRL + T)

### ISSUE THREAD

**Issue by Ciantic** [mrmlnc/vscode-scss#12]
This is a feature request, if I hit Ctrl + T (# in the vscode omnibar) it can't find symbols project/folder wide. 

I find it really useful in TypeScript and other languages where it works, allows me to travel to symbol in the project just by name.

Ctrl+O for file specific symbol listing works.

Keep up the good work, even now it's better than the vscode's inbuilt thing.

**Comment by mrmlnc** [comment]
Available in version **0.5.0**.
