### ISSUE TITLE
Function arguments not present in autocomplete list

### ISSUE THREAD

**Issue by BladeMF** [mrmlnc/vscode-scss#122]
- VS Code Version: 1.46.1
- SCSS IntelliSense Version: 0.9.0
- Operating System: Windows 10

Reproducible Case:

Steps to Reproduce:

1. Create a scss file (_empty.scss)
2. Put the following code:
```
@function func1($arg1, $arg2) {
	$b: 
};
```
3. Place your cursor after the semicolon.
4. Type `$`

*Expected result*: Suggestion list opens and `$arg1` and `$arg2` to be present in the list (and on top)
*Actual result*:
![image](https://user-images.githubusercontent.com/12109622/87020747-f7a56900-c1dc-11ea-8672-4b7f9aa21218.png)

**Comment by mrmlnc** [comment]
This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code. Please file your issue to [`vscode`](https://github.com/microsoft/vscode) repository.
