### ISSUE TITLE
Longer CSS properties show up before shorter ones

### ISSUE THREAD

**Issue by dandelionsam** [mrmlnc/vscode-scss#125]
- VS Code Version: 1.48.0
- SCSS IntelliSense Version: 0.9.0
- Operating System: Catalina 10.15.6

Title is pretty much self-explanatory, and you can view my tiny issue in the attachment below.
I think is more practical shorter properties (like simple **margin** or **padding**) shows up **before** longer versions of the same ones (like **margin-top** or **padding-bottom**). I was thinking about a _alphabetical order_ o some sort of syntax _order options_ in which you could establish which properties show up first.

![Screen Recording 2020-08-14 at 16 25 37](https://user-images.githubusercontent.com/35459772/90260250-85fbb300-de4b-11ea-9b05-b32c357ab80a.gif)

**Comment by mrmlnc** [comment]
This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code. Please file your issue to [`vscode`](https://github.com/microsoft/vscode) repository.
