### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Gaye0523** [mrmlnc/vscode-scss#128]
- Issue Type: `Performance`
- Extension Name: `vscode-scss`
- Extension Version: `0.9.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\GAYEBE~1\AppData\Local\Temp\mrmlnc.vscode-scss-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mrmlnc** [comment]
Hello, @Gaye0523,

[Please use the template](https://github.com/mrmlnc/vscode-scss/issues/new?assignees=&labels=&template=perf.md) for reporting performance issue. Based on the current information, I can't help you.
