### ISSUE TITLE
Color preview in variables

### ISSUE THREAD

**Issue by druellan** [mrmlnc/vscode-scss#13]
Since VSCode has an internal color preview system, I wonder how difficult could be to preview colors inside SCSS variables like Atom + Pigments:

![2016-10-26_08h34_53](https://cloud.githubusercontent.com/assets/6965667/19724509/126368b0-9b57-11e6-9ffb-2c8e0e969548.png)

**Comment by sethstha** [comment]
This will be easy. Since VSCode team are planning to add color support for `variables` in future. We will only need to highlight color on iltelisense.

Have a look at here.
https://github.com/Microsoft/vscode/issues/21705

**Comment by PixelT** [comment]
Any news here?

**Comment by mrmlnc** [comment]
Nope, I have no time right now. Sorry 😢

**Comment by webdevbrian** [comment]
Any news yet?

**Comment by octref** [comment]
#64 offers a solution. It doesn't handle all cases, but is useful enough IMO:

![image](https://user-images.githubusercontent.com/4033249/68788070-897db780-05f7-11ea-8e73-ec5f2ed65160.png)

**Comment by Levdbas** [comment]
Would it be possible to show the color as well when the variable is placed in the code? Right now it only shows up when suggesting a variable. I think this will be very helpful to quickly scan your scss for color variables.

**Comment by octref** [comment]
@Levdbas There are other extensions that do that. I think it's not in the scope of this extension.

**Comment by dkniffin** [comment]
@octref Which extension are you referring to? It doesn't seem that vscode-pigments handles scss variables right now. I can open an issue over there, but if there's an extension that works, I'd be happy to start using it instead.

**Comment by sethstha** [comment]
@dkniffin have you gave a try to colorize?

**Comment by dkniffin** [comment]
@sethstha That worked! Thanks!

**Comment by raedlime** [comment]
@sethstha Finally! Thx dude!
