### ISSUE TITLE
Seems to not work with Apple Silicon

### ISSUE THREAD

**Issue by betabong** [mrmlnc/vscode-scss#131]
- VS Code Version: 1.53.0-insider
- SCSS IntelliSense Version: 0.9.0
- Operating System: macOS 11.0.1

Reproducible Case: As soon as I open a SCSS file, "SCSS IntelliSense initialization" appears in the status bar and never vanishes.

Steps to Reproduce:

1. Open SCSS file in latest Intellisense insider on a Mac with M1 processor

I unfortunately don't know where to look for a log.

**Comment by jimblue** [comment]
Confirmed on my MacBook Air M1 with `Big Sur v11.2.1` and `VSCode - Insider v1.54.0`

**Comment by rriver** [comment]
I also confirmed on my M1 Mac mini with macOS Big Sur 11.2.1 and VSCode 1.54.0-insider (Universal). It does not happen on VSCode 1.53.2.

**Comment by benjibee** [comment]
Still seeing this issue with VSCode 1.54.2 on an M1 MacBook Air. This extensions doesn't seem to be maintained anymore, however.

**Comment by jimblue** [comment]
Hey @mrmlnc, how are you ?

This plugin really is a game changer when working with SCSS on VsCode
and it's really sad to see it dying... 😢 

Could you please give us your input on this issue and let us know if we can help fixing it ? 💪 

Cheers

**Comment by mrmlnc** [comment]
I have published a new version of the extension ([`0.9.1`](https://github.com/mrmlnc/vscode-scss/releases/tag/0.9.1)), which I believe should fix the work on ARM processors.

I don't have a laptop with an ARM processor, so please tell me if the problem is solved.

**Comment by jimblue** [comment]
It's working on my Macbook Air M1...
SCSS Intellisense is back in business 🎉  !
Thank you so much @mrmlnc ❤️
