### ISSUE TITLE
Error: Request initialize failed with message: The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by maxjf1** [mrmlnc/vscode-scss#133]
- VS Code Version: 1.53.2
- SCSS IntelliSense Version: v0.9.0
- Operating System: Ubuntu 20.10

The extension is showing the following message (it wasn't showing it before):

    Request initialize failed with message: The "path" argument must be of type string. Received null

![image](https://user-images.githubusercontent.com/6114888/108719935-f53f1780-74fe-11eb-8252-e7cda9f72e66.png)

Reproducible Case:
IDK exactly how to reproduce. I just opened the IDE and it sarted showing. The only settings i've changed was:

```json
{
    "scss.scannerExclude": [
        "**/.git",
        "**/bower_components"
    ],
    "scss.showErrors": true,
}
```

**Comment by maxjf1** [comment]
Here is the errors displayed on the console
![image](https://user-images.githubusercontent.com/6114888/108861487-07d45200-75ce-11eb-8038-de50fcefb731.png)

**Comment by mrmlnc** [comment]
I ship the next version (`0.10.0`) of this plugin to the VS Code Marketplace. Is the problem still there?

If so, please provide more information about your environment. If there is an opportunity to provide a project (on GitHub, as archive on email) or a minimally reproducible case (better case), it would help a lot.
