### ISSUE TITLE
scss color 

### ISSUE THREAD

**Issue by skandasoft** [mrmlnc/vscode-scss#136]
Colors don't show up on the .scss files because I am using @use rather than @import. Not sure if it from here or css editor I have to put the issue in the color highlighter plugin

**Comment by mrmlnc** [comment]
It seems to me that this is fixed in the `master` branch and will be shipped in the `0.10.0` version.

![8MAQtdTOjd](https://user-images.githubusercontent.com/7034281/117548316-fd5a1e00-b03c-11eb-8867-0ec690af71d8.gif)

Let me know if I'm wrong.
