### ISSUE TITLE
Suggestions in the middle of a string

### ISSUE THREAD

**Issue by druellan** [mrmlnc/vscode-scss#22]
Seems that some characters trigger the suggestions on invalid places.

To reproduce, type:
`background-image: url(../invalidstring/);`
Now, move out of the line, and in again, and start completing the path before the last `/`

![2016-10-30_16h48_05](https://cloud.githubusercontent.com/assets/6965667/19839447/a0722792-9ec0-11e6-83b4-af15df2ca810.png)

**Comment by mrmlnc** [comment]
Hello, @druellan,

Firstly, thank you for your interest 👍. Now plugin doesn't check the context for completion provider.

Unfortunately, I don't have any time at the moment, so this bug will be fixed in version 0.6.0.

**Comment by druellan** [comment]
Thanks! and no pressure! Just pointing out things I've found while using the plugin.

**Comment by mrmlnc** [comment]
Should be fixed in `vscode-scss@0.6.0`.
