### ISSUE TITLE
Suggestions too general on VS Code 1.7.1

### ISSUE THREAD

**Issue by Enamex** [mrmlnc/vscode-scss#24]
This was true on VS Code 1.6 as well.

The suggestions shown on Ctrl+Space are very, very general (I think it just lists everything that can be written in the file that it knows about) and don't care about where the auto-complete is invoked.

If I say something like:

```scss
#someid {
    float: |
}
```
And invoke the auto-complete where the pipe is, I get a list of all symbols currently used in this file plus a plethora of useless stuff; it doesn't list just left, right, etc., which is what I'd expect from auto-complete (VS Code does that with plain CSS).

Thank you.

**Comment by mrmlnc** [comment]
Hello, @Enamex,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code.

**Comment by Enamex** [comment]
Might it be interfering with what VS Code adds?

Because in CSS mode VS Code shows relevant suggestions normally in this position at least, while in SCSS it's showing SCSS variables that don't even fit the field (say, a number variable for the `float` field).

**Comment by mrmlnc** [comment]
I think I can add `scss.excludeProperties` option. For example:

```json
{
  "scss.excludeProperties": [
    "float",
    "display"
  ]
}
```

What do you think about this?

**Comment by mrmlnc** [comment]
Closed because we don't have feedback from user.
