### ISSUE TITLE
Map type ) expected

### ISSUE THREAD

**Issue by yordis** [mrmlnc/vscode-scss#25]
Hey I created a map and for some reason I see: ) expected and probably because of that I see the second error: colon expected

![screen shot 2016-11-16 at 3 51 57 am](https://cloud.githubusercontent.com/assets/4237280/20354799/455964f8-abed-11e6-9732-399b0bc415c2.png)

**Comment by mrmlnc** [comment]
Hello, @yordis,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code.

See: https://github.com/Microsoft/vscode/issues/15410, https://github.com/Microsoft/vscode/issues/8678, https://github.com/Microsoft/vscode/issues/7434, https://github.com/Microsoft/vscode/issues/1758
