### ISSUE TITLE
Hover/Command+Hover broken for & selector

### ISSUE THREAD

**Issue by yordis** [mrmlnc/vscode-scss#26]
Notice in the screenshot the selector said undefined--auto. Also I think because of this the example next to the selector is wrong as well should be boa-container__column--auto

![screen shot 2016-11-16 at 3 59 14 am](https://cloud.githubusercontent.com/assets/4237280/20354815/5806dea0-abed-11e6-8c01-d2e40f11d0a0.png)

**Comment by mrmlnc** [comment]
Hello, @yordis,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code.

You can create this issue in https://github.com/Microsoft/vscode
