### ISSUE TITLE
Off topic: any plans on a "vscode-js" ? 

### ISSUE THREAD

**Issue by jlc467** [mrmlnc/vscode-scss#28]
It would parse for symbols in js files and autosuggest them within any js file.

So if i have `foo.myFunction` in File A, within File B, if i start typing `my` it would autosuggest `myFunction`.

Pretty positive there is strong demand, see:
https://github.com/Microsoft/vscode/issues/12115
https://news.ycombinator.com/item?id=12229239

Thanks!

**Comment by mrmlnc** [comment]
No, now I'm not thinking about it.
