### ISSUE TITLE
Feature request: "Go to definition" for @imports

### ISSUE THREAD

**Issue by andi1984** [mrmlnc/vscode-scss#30]
Would love to see integration of the "go to definition" working for @imports like:

```sass
// -------------------------------------
//   Settings
// ——————————————————
@import "settings.fonts";

// -------------------------------------
//   Tools
// ——————————————————
@import "tools.molten-leading";
```

by clicking on `tools.molten-leading` it should open `_tools.molten-leading.scss` in the same folder. Any plans on that?

**Comment by octref** [comment]
This is already provided by VS Code's SCSS support.

**Comment by etiennejcharles** [comment]
Was anyone able to get it to work ? If so - I'de be curious how 
I'm facing the same issue, never really was able to get it to work
