### ISSUE TITLE
Resolve `~` paths to node_modules

### ISSUE THREAD

**Issue by Ciantic** [mrmlnc/vscode-scss#31]
The [blueprintjs](https://github.com/palantir/blueprint) framework has SCSS variables file located in:

`node_modules\@blueprintjs\core\dist\variables.scss`

I can't seem to import it so that it can be used in auto-completions.

I've tried: 

```
// <reference path="../node_modules/@blueprintjs/core/dist/variables.scss" />
// and
@import "~@blueprintjs/core/dist/variables.scss"; // This is webpack's way of importing things from node_modules, this would be ideal to support
// and
@import "../node_modules/@blueprintjs/core/dist/variables.scss";
```

None of the above work, I just cant get the code completion to work.

Any ideas how I could? There is a lot of variables there I need constantly.

**Comment by Ciantic** [comment]
I wonder if that `scannerExclude` default is affecting that. It's not ideal if exclusion works also for explicitly typed imports.

**Comment by mrmlnc** [comment]
## Temporary fix

Set in the `settings.json` and **restart** editor:

```js
	"scss.scannerExclude": [
		"**/.git",
		"**/bower_components"
	]
```

## Solution

We need refresh **Storage** if user changed settings. Now this plugin update only current file. Moved to `1.0.0`.

**Comment by Ciantic** [comment]
The workaround is not working anymore because the vscode-SCSS now dies when I'm using this:

(I still need this for webpack to work)
```
@import "~@blueprintjs/core/dist/variables.scss";
```

It dies in the developer tools like this:

```
Object {errno: -4058, code: "ENOENT", syscall: "stat", path: "c:\Source\HTML5\testApp\~@blueprintjs\core\dist\variables.scss"}
```

Then none of the completions work, I suspect the aboe is the reason. Could vscode-scss ignore files it can't resolve or find?

**Comment by Ciantic** [comment]
Found a new workaround: 

```
"scss.scanImportedFiles" : false
```
This makes it working again.

**Comment by octref** [comment]
I made `~` to resolve into node_modules:

![image](https://user-images.githubusercontent.com/4033249/68811276-1db24380-0625-11ea-814b-4bef0b6c0194.png)
