### ISSUE TITLE
Support for indent-based `.sass` files?

### ISSUE THREAD

**Issue by andrewmartin** [mrmlnc/vscode-scss#32]
Hi, I did my best to research this but wasn't finding anything obvious; this works excellent for `.scss` files, but does it work (or is there any way to configure it to work?) with `.sass` files?

**Comment by mrmlnc** [comment]
Hello, @andrewmartin,

This plugin only works with SCSS syntax. We use a parser (https://github.com/Microsoft/vscode-css-languageservice) that does not support Sass syntax.

**Comment by andrewmartin** [comment]
Ahh, good to know, thank you @mrmlnc ! May I submit a PR (or would you consider) an add to README for future reference?
