### ISSUE TITLE
`/deep/`selector breaks code highlighting 

### ISSUE THREAD

**Issue by DethAriel** [mrmlnc/vscode-scss#33]
<img width="206" alt="screen shot 2017-02-08 at 6 56 33 pm" src="https://cloud.githubusercontent.com/assets/1497789/22767488/592679a0-ee30-11e6-84ea-9e0993b2c641.png">
If you add the `/deep/` selector, then code highlighting is broken, it just says `[scss] { expected`

**Comment by mrmlnc** [comment]
Hello, @DethAriel,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code.

**Comment by cedvdb** [comment]
How do you figure it's related to vs code ? There is no error prior to installing the extension.

**Comment by bcruddy** [comment]
@DethAriel did you ever find a solution here? I'm ok moving to another plugin. It looks like vscode isn't going to support the `/deep/` selector https://github.com/Microsoft/vscode/issues/7002
