### ISSUE TITLE
Intellisense freezes at random instances.

### ISSUE THREAD

**Issue by sqnkov** [mrmlnc/vscode-scss#35]
Hello @mrmlnc  , I've been trying to figure out an issue with the SASS intellisense and I tried contacting the guys from Microsoft, but they can't figure out why this is happening in vscode.

So I guess the next natural step would be to contact You, since it might be a plugin-related issue as well.

Here is the **[thread](https://github.com/Microsoft/vscode/issues/19840#issuecomment-279004031)** in which the issue is being discussed and acted upon. 

If you have the time, please check this out.

**Comment by mrmlnc** [comment]
Hi, @sqnkov,

You say that the problem has been reproduced, even if all the extensions turned off. Then this is not related to this plugin.

But I have similar problem with Python extension on my MacBook Air: when I close the lid (go to sleep), and then open it, then sometimes autocompletion stops working.

**Comment by mrmlnc** [comment]
Closed for https://github.com/Microsoft/vscode/issues/19840#issuecomment-281023186
