### ISSUE TITLE
extension  doesn`t  work

### ISSUE THREAD

**Issue by Aaronphy** [mrmlnc/vscode-scss#36]
Yesterday, It works  well....

But  today, it doesn`t work ....

How can  fix it..

**Comment by mrmlnc** [comment]
Sorry, but I'm not a [Baba Vanga](https://en.m.wikipedia.org/wiki/Baba_Vanga)(clairvoyant).

Need more detailed information, because it's works fine for me with VS Code 1.9.1.

**Comment by mrmlnc** [comment]
Closed, because we have no feedback.
