### ISSUE TITLE
Intellisense is confusing

### ISSUE THREAD

**Issue by ArkhipovK** [mrmlnc/vscode-scss#38]
While using the itellisense within sass file, i've noticed that the proposed list of values is huge and arranged in alphabetical order.  I think it much more useful when the order is based on type of value. Is is possible?
![default](https://cloud.githubusercontent.com/assets/9945452/23502183/b8644472-ff58-11e6-85dd-7023e3cf9ed2.png)

**Comment by ArkhipovK** [comment]
Why invalid?

**Comment by mrmlnc** [comment]
Hello, @ArkhipovK,

The `vscode-scss` (this plugin) provide not sorted array of Symbols from all `.scss` documents from current workspace to VS Code. Your feature request related to VS Code team.
