### ISSUE TITLE
Cannot find module client.js

### ISSUE THREAD

**Issue by BhaskaranR** [mrmlnc/vscode-scss#43]
Getting this exception. search for it online couldn't find a resolution. 

Activating extension `mrmlnc.vscode-scss` failed: Cannot find module '/Users/bhaskarferrari/.vscode/extensions/mrmlnc.vscode-scss-0.6.2/out/client.js'.

**Comment by mrmlnc** [comment]
If you use the plugin from this repository, then you first need to compile it.

For more details see https://github.com/mrmlnc/vscode-scss/blob/master/package.json#L124 or any script from `scripts` section.

**Comment by BhaskaranR** [comment]
I installed the extension. shouldn't it be built already?

**Comment by mrmlnc** [comment]
Sorry, but I don't uderstand you. You must use this instruction:

https://github.com/mrmlnc/vscode-scss#install

**Comment by BhaskaranR** [comment]
i installed it already, but still get the error
![screen shot 2017-05-28 at 9 17 31 am](https://cloud.githubusercontent.com/assets/11024551/26529053/abf93202-4386-11e7-83fa-2054d862d70e.png)

**Comment by mrmlnc** [comment]
I publish my extension with all files. Most likely your problems related to VS Code or your firewall/antivirus and more, more, more...
