### ISSUE TITLE
Feature request: Comment Tag that is indexed by Go To Symbol

### ISSUE THREAD

**Issue by viperfx07** [mrmlnc/vscode-scss#44]
Use {{ and }} to wrap a keyword inside comment, then this keyword (comment tag) will be indexed by the Goto Symbol and Goto Definition features.

It's useful especially for BEM users, to find
<img src="https://camo.githubusercontent.com/05692cf0f34dc1cbe30ff2909dc450ac3580abe9/68747470733a2f2f703233332e6769746875622e636f6d2f53796e7461782d686967686c69676874696e672d666f722d536173732f30382e676966">

https://github.com/P233/Syntax-highlighting-for-Sass#comment-tag

**Comment by mrmlnc** [comment]
Hell, @viperfx07,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code.
