### ISSUE TITLE
Colons before pseudo-selectors

### ISSUE THREAD

**Issue by wonkeythemonkey** [mrmlnc/vscode-scss#45]
In definitions for pseudo-selectors, such as `:first-child` or `:last-of-type`, the leading colon is not detected as part of the user input.

## Desired Behavior
If I type `:fi`, the suggestions dropdown should appear with `:first-child` as the top option. If I were to select that option from the dropdown, my text should auto-expand to:
`:first-child`

## Current Behavior
If I type `:fi`, the suggestions dropdown appears with `:first-child` as the top option. If I select that option from the dropdown, my text auto-expands to:
`::first-child`

The current workaround is to not type the leading colon, but that is a difficult habit to break.

**Comment by mrmlnc** [comment]
Hello, @wonkeythemonkey,

This extension provides suggestions only for SCSS symbols (variables, Mixins and functions) from all SCSS files in workspace. Everything else adds VS Code. Your problems related to VS Code.
