### ISSUE TITLE
Plugin crashes with importing an external URL

### ISSUE THREAD

**Issue by Falco101** [mrmlnc/vscode-scss#46]
So there's the existing problem of not being able to import partials the Sassy way like `@import 'Variables'` and instead having to do `@import '_Variables.scss'`, which is at least fixable, but annoying. 

However, importing cdn hosted Sass is also causing the plugin to crash and I'm not sure how to work around it. Example: this web font `@import url('https://fonts.googleapis.com/css?family=Aguafina+Script');` which Atom's native Sass intelisense had no issue with but unfortunately crashes this plugin. Is there any workaround like with importing partials? Or is this something that simply cannot be done at this time?

**Comment by mrmlnc** [comment]
Closed in favor of #49
