### ISSUE TITLE
Go To Definition Provider Showing its own instance as definition

### ISSUE THREAD

**Issue by charrondev** [mrmlnc/vscode-scss#47]
This seems to have cropped up recently, where the go to definition provider that seems to have been [resolved in 0.6.2](https://github.com/mrmlnc/vscode-less/issues/36) has come back. When hitting "Go To Definition" on a mixin the editor considers the link being click to be an instance and requires a few extra clicks to actually go to the definition.

Example: 

![image](https://user-images.githubusercontent.com/1770056/26993108-bc3d75da-4d2f-11e7-9d7f-a3773ff8f2ee.png)

**Comment by mrmlnc** [comment]
The problem present in the latest version of the plugin? Right now I cannot reproduce this issue. Any suggestions how to I can reproduce the problem?

**Comment by charrondev** [comment]
It's likely not present anymore (I saw this plugin got some significant updates anyways). In any case I don't actually use Sass anymore, so it can just be closed.
