### ISSUE TITLE
Duplicate variable suggestion

### ISSUE THREAD

**Issue by PixelT** [mrmlnc/vscode-scss#54]
After enable extension I have duplicate suggestion for variable (see screenshot):

![duplicate variable suggestion](https://i.imgur.com/Q28dGkC.png)

When I try to write variable from another file it's OK (I have only 1 item on list)
Duplicate value exist only when I declare & want to use variable in this same file.

**Comment by raldred** [comment]
Same
https://www.dropbox.com/s/kp2wwl230ljwbjj/Screenshot%202017-11-28%2010.44.04.png?dl=1
![screenshot 2017-11-28 10 44 04](https://user-images.githubusercontent.com/37096/33315635-24356096-d429-11e7-8936-deb4583212fc.png)

**Comment by mrmlnc** [comment]
Will be fixed with #94. After that, we will exclude the local symbols (from the current document) from the hints.
