### ISSUE TITLE
Parameter info doesn't show up

### ISSUE THREAD

**Issue by dehghani-mehdi** [mrmlnc/vscode-scss#56]
Hi,

Thanks for `vscode-scss`, I don't know it's a bug or missed feature, but the parameter info/description for `mixin` doesn't show up.

For example:

```
/// Change body's color
///
/// @access public
///
/// @param {String} $color
///     color code/name
///
@mixin test($color) {
    body {
        color: $color;
    }
}
```

The comment that I wrote for `$color` or mixin itself doesn't show up when I want to use it.

Thanks again.

**Comment by mrmlnc** [comment]
```
/// Change body's color
///
/// @access public
///
/// @param {String} $color
///     color code/name
///
```

This is official docstring for Sass? You can provide documentation for this?

**Comment by dehghani-mehdi** [comment]
I could not find any official docs about that, but popular libraries like `Bourbon` use this syntax.

Example: https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/helpers/_buttons-list.scss

**Comment by Varkal** [comment]
Support for SassDoc should be very a very useful features

The documentation is [here](http://sassdoc.com/annotations/)

**Comment by patoezequiel** [comment]
I'm experiencing the same. This would greatly increase the utility of suggestions.

**Comment by shiftgeist** [comment]
Would be very exited to see this being integrated, this would be very helpful when working with mixins and maps, which could be possible when https://github.com/SassDoc/sassdoc/issues/386 is closed.
