### ISSUE TITLE
Support for CSS / PostCSS variables

### ISSUE THREAD

**Issue by onetrev** [mrmlnc/vscode-scss#58]
It's a big ask, but as you've already kindly built support for cross file reference for Less and Sass.... Any chance you've considered doing the same for CSS? In other words, for those using PostCSS, it would be awesome to have _Autocomplete and Go to Declaration and Find References_ for CSS Variables!!

It seems crazy that VS Code doesn't include this for these languages by default though and have no plans still to do so! So sad. :( 

PS, you should add a PayPal donate option as well, I can't seem to get Gratipay to work.

**Comment by mrmlnc** [comment]
Sorry for slow answers. I've had zero spare time for the past couple of weeks.

I want to work on universal code-base for similar plugins (Less + SCSS) in the first half of next year. It seems that to add support for CSS is very simple. I understand that this is a very popular plugin and it requires support.

You can use PayPal button from https://github.com/mrmlnc/scandir-native#donate repository, for example, if you wanted.

**Comment by onetrev** [comment]
No worries on the delay, all good. Great to hear you are looking at something to support CSS / PostCSS (CSSNext). Definitely CSS custom properties / variables support is key. 

You are right PostCSS is definitely lacking support in VS Code, but it's getting really popular and usage of PostCSS is growing fast as people slowly start to move to it from Less/Sass. Thanks!

**Comment by octref** [comment]
I believe this is out of the scope of this project. You can follow https://github.com/microsoft/vscode/issues/28459 instead.
