### ISSUE TITLE
No intellisense following the '@' symbol

### ISSUE THREAD

**Issue by ndstephens** [mrmlnc/vscode-scss#59]
While in any '*.scss' file if i begin typing the '@' symbol i don't get any intellisense such as '@function' or '@mixin' or '@each' options.

After fully typing one out they are recognized throughout the other files.  Everything appears to work as intended and i get intellisense when using them (including variables), but none when trying to create anything that begins with the '@'.  Hopefully i'm making sense.

**Comment by octref** [comment]
This is already done by VS Code's SCSS support.

![image](https://user-images.githubusercontent.com/4033249/68704431-26314e00-0541-11ea-9f4d-bf28c9a8e944.png)

The only one missing is `@function`, which I just added in https://github.com/microsoft/vscode/issues/84617
