### ISSUE TITLE
Native properties and their values

### ISSUE THREAD

**Issue by Kcko** [mrmlnc/vscode-scss#61]
Native css properties and their values are behind scss variables.

Example: When i write float: (ctrl enter) i expect list of float values (left /right) and after scss variables / mixins ... 

Now i see all scss variables from all files and then follow float values  
see https://goo.gl/YfnpxL

How to solve it? 

Many thx.

**Comment by Kcko** [comment]
Still no reply? Is extension still in developoment or deep in hell? Im unistalling ...

**Comment by octref** [comment]
See https://github.com/microsoft/vscode/issues/74213. There's no fix from the extension. VS Code needs to fix it.
