### ISSUE TITLE
Resources overload on Ubuntu 

### ISSUE THREAD

**Issue by victorpavlov** [mrmlnc/vscode-scss#63]
Hi! I found a bug with this extension.

When plugin is active, and I'm opening the `.scss` file from my project, the process initiated by plugin permanently loads CPU up to 30%-40% and eats memory, may take all available system memory if not stopped.

When the extension is disabled no memory or CPU leaks.

I did not test it on several projects, but the project which I use contains many `.scss`, something about 300-400 files in up to 10 folders.

**System info:**

- Linux Ubuntu 17.10,
- VSCode 1.20.0 Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
- Date 2018-02-07T17:10:15.949Z

**Comment by lolmaus** [comment]
For me, this extension eats 100% of one CPU core, which is outrageous.

**Comment by lewayjack** [comment]
the same issue. enable scss intellisense lead to a very high CPU usage.
CPU %	Mem MB	   PID	    Process
135	        221	           6914	       electron_node server.js

**Comment by octref** [comment]
Please try 0.8.0 and file a new issue with a profile, thanks: https://github.com/mrmlnc/vscode-scss/issues/new?template=perf.md

(Or you can reopen and attach profile here)
