### ISSUE TITLE
Support for vue files (variable suggestions, mixins etc.) 

### ISSUE THREAD

**Issue by helloroman** [mrmlnc/vscode-scss#66]
Hello, 
i'm struggling to find a way to get variables and mixins suggestions in .vue files. Is there a way to support vue files with vscode-scss plugin?

**Comment by KevisLuo** [comment]
any update for this?

**Comment by synapse709** [comment]
I would also love vue support for this

**Comment by mrmlnc** [comment]
Will be fixed with `0.9.0`.

**Comment by urielvan** [comment]
@mrmlnc May I ask when `0.9.0` will be released? Since it's quite useful working with vue.
