### ISSUE TITLE
add option to exclude extension and leading underscore on `@import`

### ISSUE THREAD

**Issue by selrond** [mrmlnc/vscode-scss#68]
Current behavior (autocompletes to):

```scss
@import '_header.scss';
```

Wanted behavior (with disabled file extension and leading underscore):

```scss
@import 'header';
```

**Comment by octref** [comment]
This feature is already supported by VS Code's SCSS support.

**Comment by dkniffin** [comment]
@octref I know this is an old issue, but I'm running into the same issue. Can you share how I would configure VSCode to exclude the extension when adding an import?
