### ISSUE TITLE
Gratipay/Donate no longer works

### ISSUE THREAD

**Issue by missmatsuko** [mrmlnc/vscode-scss#71]
Just an FYI. Looks like Gratipay went down sometime in 2017 and was replaced by Liberapay:
https://gratipay.news/vive-la-liberapay-14057a25eacb

**Comment by octref** [comment]
@mrmlnc Do you have a new donation link? If so can you update the link to donation could go to you?

**Comment by mrmlnc** [comment]
I've updated the donations section. If someone sends a donation, I'm willing to share it with you. Maybe in the future we can switch to GitHub Sponsor with Open Collective, but not now.

**Comment by octref** [comment]
It's ok, just take the donation, I'm doing this as part of my work 😉
