### ISSUE TITLE
Feature Request: Include other file extensions

### ISSUE THREAD

**Issue by eyekanspele** [mrmlnc/vscode-scss#72]
I would like this plugin to recognize other file types that are primarily scss files.

For instance I do Shopify theme development, and Shopify uses scss files with an extension of .scss.liquid; my main style sheet is "styles.scss.liquid" and it would be nice for the intellisense to work with this file since the majority of it is scss, with a few liquid tags that Shopify will insert things like color settings.

I envision an option similar to the exclude.

scss.scannerInclude
Type: string[]
Default: [".scss.liquid"]

**Comment by eyekanspele** [comment]
I have found adding the following to my user settings solves this problem, however I imagine a setting at the plugin level would still be useful.

`"files.associations": {"*.scss.liquid": "scss"} `

**Comment by octref** [comment]
You should use `files.association` — this extension only cares about SCSS files so you should make sure whatever files you care would be marked as SCSS files in VS Code.
