### ISSUE TITLE
Performance in large project is bad

### ISSUE THREAD

**Issue by PixelT** [mrmlnc/vscode-scss#73]
I have project on magento2, where it's a lot of files, and the autosuggest with variables doesn't work. 
I still have:

![https://i.imgur.com/mOe9s5r.png](https://i.imgur.com/mOe9s5r.png)

I tried to exclude a lot of folders by using `scss.scannerExclude` option, but it didn't help...

**Comment by octref** [comment]
@PixelT Please try 0.8.0 and file a new issue with a profile, thanks: https://github.com/mrmlnc/vscode-scss/issues/new?template=perf.md

(Or you can reopen and attach profile here)
