### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#78]
Hello, friends,

Unfortunately, I can't support this project. I would really love to find a developer that would like to breath new life into the project and continue its development. Reply to this issue if you find yourself interested in owning this plugin.

**Comment by growtofill** [comment]
Hey Denis,

Thanks for making this extension! Could you briefly describe maintainer's responsibilities from your point-of-view?

**Comment by octref** [comment]
See #83, I'll help a bit with the maintenance.
