### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by blizzrdof77** [mrmlnc/vscode-scss#80]
- Issue Type: `Bug`
- Extension Name: `vscode-scss`
- Extension Version: `0.6.2`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by octref** [comment]
You have not provided enough detail to debug the issue.

**Comment by blizzrdof77** [comment]
Sorry that must have been an automated feature in VSCode that I somehow triggered. Please disregard!
