### ISSUE TITLE
Revive development and publish 0.8.0

### ISSUE THREAD

**Issue by octref** [mrmlnc/vscode-scss#83]
As an effort to close microsoft/vscode#6734, I'll help a bit with development on this repo.

I have asked @mrmlnc and he kindly gave me committer access.

I have no plan to make drastic changes soon. My short term plan is:

- Bring the infrastructure up-to-date by adding CI, updating the linter, dependencies, etc
- Add end-to-end integration tests
- Add a guide for reporting performance issues. Identify the cause of perf issues and fix it.
- Allow analysis and imports from `node_modules`. #31 
- Go through PRs and Issues

Here are my plan for making a new release, 0.8.0.
I'll update the list as I go.

---

- [x] Bring CI back (Travis)
- [x] Add an issue template
- [x] Add a guide for filing perf issues #89
- [x] Go through issues
- [x] Go through PRs
- [x] Add end-to-end test with Travis #88
- [x] Update linting infrastructure tslint
- [x] Update formatting infrastructure with prettier

**Comment by mrmlnc** [comment]
So, I can move CI to Azure Pipelines quickly

Something like https://github.com/mrmlnc/emitty/tree/master/.vsts, but only for Node.js 12 (electron@6+).

**Comment by KytoSai** [comment]
Thank you for your continued development this extension

Are you plan to support sass module ? 

Thanks you !

**Comment by octref** [comment]
@KytoSai No, sadly nobody has support for sass :(

**Comment by KytoSai** [comment]
Really sad because this extension is essential !

Thank you !

**Comment by octref** [comment]
@mrmlnc When 0.8.0 is ready, do you want to release it or do you want me to do it?

If you want me to do that you would need to add me to your https://marketplace.visualstudio.com/manage/publishers

**Comment by mrmlnc** [comment]
I will publish the release as soon as it is required.

You can help me by creating a release on GitHub with changelog.

**Comment by octref** [comment]
@mrmlnc I made https://github.com/mrmlnc/vscode-scss/releases/tag/v0.8.0. Please feel free to edit and publish to the marketplace. Thanks for collaborating with me!

**Comment by mrmlnc** [comment]
Version `0.8.0` is available in the marketplace.
