### ISSUE TITLE
Ignore paths, implicitly import and completion

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#9]
> In fact, too well:
> ![image](https://cloud.githubusercontent.com/assets/7034281/19696402/9cc0b87c-9aef-11e6-9fb0-4935a86f372b.png)
> Perhaps a way to ignore a path is needed. Also, not sure if the "implicitly" is so useful that worth taking up space for the path and the variable contents.
> Another thing I noticed, and this can be a VScode problem:
> ![image](https://cloud.githubusercontent.com/assets/7034281/19696415/ad15b4c0-9aef-11e6-83a5-621db8a97d56.png)
> If you write the property, hit ctrl+space and then you keep typing, the autocomplete is not refreshed.
> @druellan

**Comment by mrmlnc** [comment]
@druellan,

> Perhaps a way to ignore a path is needed.

You can use `scss.scannerExclude` option.

> Also, not sure if the "implicitly" is so useful that worth taking up space for the path and the variable contents.

I saved WebStorm behavior in this plugin. Need to think about it.

> Another thing I noticed, and this can be a VScode problem:

Should be fixed in 0.3.1.

**Comment by druellan** [comment]
Thanks!
Yes. I'm not a hardcore scss dev, so, perhaps I'm missing something, but I believe the most important information is the filename of the scss file.

**Comment by mrmlnc** [comment]
I'll add settings for this case `scss.showImplicitlyLabel` in 0.3.2.

**Comment by druellan** [comment]
Thanks! Ready to test on the next push.

**Comment by druellan** [comment]
BTW, you can try also reduce the space using an abbreviation, for example (imp) and (exp), I believe is clear enough.

**Comment by mrmlnc** [comment]
@druellan, in version **0.5.0** `scss.showImplicitlyLabel` renamed to `scss.implicitlyLabel` and supports custom messages.
