### ISSUE TITLE
Does not open files that start with _

### ISSUE THREAD

**Issue by javierartero** [mrmlnc/vscode-scss#90]
- VS Code Version: 1.40.1
- SCSS IntelliSense Version: 0.8.0
- Operating System: Mojave 10.14.6

Reproducible Case:

Steps to Reproduce:

1. Create a file that starts with the _ character, for example `_variables.scss` with a test variable

2. Import it `@import 'variables';`

3. Create a rule that uses that variable

4. When you click + alt to access the file that includes it, it does not find it, the path appears correctly but without the character `_`

**Comment by octref** [comment]
I cannot reproduce this bug on macOS:

Auto-completion works for me, and upon cmd+clicking `variables` I jump to `_variables.scss`. What are you doing differently?

![image](https://user-images.githubusercontent.com/4033249/69077112-c11aa400-09e9-11ea-932e-6f7d128df80b.png)

**Comment by mrmlnc** [comment]
Hmm, this is a strange. I could reproduce this on the `bootstrap` repository, but I can't now. It's probably related to the code in the scanner, but I'm not sure. Anyway, I'm almost done refactoring the scanner.

**Comment by mrmlnc** [comment]
Gotcha!

* Open `scss/bootstrap.scss`
* Jump to `@import "utilities/api";`
* Jump to ` breakpoint-infix` symbol

```
[2019-11-18 21:07:25.881] [renderer1] [error] Unable to read file (Error: File not found (d:\work\OpenSource\bootstrap\scss\mixins\breakpoints.scss)): Error: Unable to read file (Error: File not found (d:\work\OpenSource\bootstrap\scss\mixins\breakpoints.scss))
    at S.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1559:715)
```

**Comment by mrmlnc** [comment]
Version [`0.8.1`](https://github.com/mrmlnc/vscode-scss/releases/tag/0.8.1) is released.

The problem must be fixed for all known cases. Please provide feedback if the problem is still observed.
