### ISSUE TITLE
Explore 'vscode-css-languageservice' as default parser for all files

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-scss#92]
Now the `scss-symbols-parser` package is outdated and has a some bugs. For example, this package does not support `@use` and cannot parse correctly the following content from Bootstrap:

```scss
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;

@include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
@include _assert-starts-at-zero($grid-breakpoints, "$grid-breakpoints");

$container-max-widths: (
  sm: 540px,
  md: 720px,
  lg: 960px,
  xl: 1140px
) !default;

@include _assert-ascending($container-max-widths, "$container-max-widths");
```

Previously we switch parser by performance issues. Right now (for me) this is not a important development direction of this plugin.

**Comment by mrmlnc** [comment]
https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss

```
vscode-css-languageservice: 82.553ms
scss-symbols-parser: 7.821ms
```

**Comment by mrmlnc** [comment]
JFYI: https://github.com/microsoft/vscode-css-languageservice/blob/00a3873c2fc080b90622d8795c170d702779c724/src/services/scssNavigation.ts#L26

**Comment by mrmlnc** [comment]
As part of this ticket, we must fix the problem in the `scss-symbols-parser`.

https://github.com/mrmlnc/scss-symbols-parser/blob/e82822155161c2e4ffed2099b3448961e6fbde84/src/index.ts#L114

```diff
- } else if (token[0] === ')' && tokens[pos + 1] && tokens[pos + 1] === ';') {
+ } else if (token[0] === ')' && tokens[pos + 1] && tokens[pos + 1][0] === ';') {
```

**Comment by octref** [comment]
Yeah, me and @aeschli would be happy if we can share the parser can fix bug together.
FYI there's already a PR for adding `@use` and I'm planning to review and pull it in soon.
