### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Xecutioner1599** [mrmlnc/vscode-scss#95]
- Issue Type: `Bug`
- Extension Name: `vscode-scss`
- Extension Version: `0.8.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.40.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by octref** [comment]
Please follow extension reporting guideline https://github.com/mrmlnc/vscode-scss/issues/new?template=bug.md
