### ISSUE TITLE
Support sass modules

### ISSUE THREAD

**Issue by octref** [mrmlnc/vscode-scss#98]
https://css-tricks.com/introducing-sass-modules/

This should be doable after https://github.com/mrmlnc/vscode-scss/pull/96.

**Comment by mrmlnc** [comment]
Confirm, it works with the #96.

<img width="446" alt="Annotation 2019-12-05 113334" src="https://user-images.githubusercontent.com/7034281/70217911-1decbd00-1753-11ea-9da0-cbb214a0e39c.png">

**Comment by mrmlnc** [comment]
Fixed by `0.9.0`.
